# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 05 Apr 2018 19:13:00 +0000
*               @ALL          0
*               @user         8
