<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: sebastian
 * Date: Mon, 14 Jan 2019 15:43:44 +0000
 */

$conf['title'] = 'wikilitic';
$conf['lang'] = 'es';
$conf['template'] = 'material';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
